version: 2
jobs:
  build:
    Working_directory: ~/myapp
    docker:
     - image: circleci/node:8-browsers
    steps:
      - checkout:
      path: ~/myapp
      - restore_cache:
	  key: angular-whishlist-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
	  key: angular-whishlist-{{ .Branch }}-{{ checksum "package-lock.json" }}
	  paths:
	      "node modules"
      - run: npm run test -- --progress=false --watch=false --browsers=ChromeHeadlessCI